language: scala
addons:
  apt:
    packages:
      - git
      - python-pip
      - python-virtualenv
scala:
   - 2.10.5
   - 2.11.6
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
  - pip install --user codecov && codecov
  - sbt 'set test in assembly := {}' pythonItAssembly
  - cd python
  - ls
  - virtualenv ve
  - source ve/bin/activate
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r test-requirements.txt
  - python setup.py install
  - python setup.py test
  - wget -P $HOME/ http://archive.apache.org/dist/spark/spark-1.6.0/spark-1.6.0-bin-hadoop2.6.tgz
  - tar -xvzf $HOME/spark-1.6.0-bin-hadoop2.6.tgz -C $HOME/
  - export PATH=$PATH:$HOME/spark-1.6.0-bin-hadoop2.6/bin
  - python setup.py integration_test --jar=drunken-data-quality.jar
  - deactivate
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/spark-1.6.0-bin-hadoop2.6
deploy:
  provider: pypi
  user: ${pypi_user}
  password: ${pypi_password}
